GET  https://www.ly.com/flights/itinerary/oneway

GET http://github.com

GET https://www.juhe.cn/docs/api

GET https://hq.sinajs.cn

GET http://finance.eastmoney.com/

GET http://finance.eastmoney.com/a/czqyw.html

#ETF
GET http://stock.eastmoney.com/bidu.html

GET http://finance.eastmoney.com/yaowen.html

GET https://www.eastmoney.com/

GET https://hq.sinajs.cn/list=sz000977,sh600756,sh512690
